---
- hosts: 172.31.35.149
  become: yes
  tasks: 
  - name: I want to install git
    apt:
     name: git
     state: present

  - name: I want to install wget
    apt:
     name: tree
     statee: present
    ignore_errors: yes

  - name: I want to install tree
    apt:
     name: tree
     state: present
